# Generated by Django 3.2 on 2023-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='打榜票数'),
        ),
    ]
