# Generated by Django 3.2 on 2023-10-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='vote_time',
            field=models.CharField(default=None, max_length=12, verbose_name='投票时间'),
        ),
    ]
