# Generated by Django 3.2 on 2023-10-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myuser_vote_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0, verbose_name='打榜票数')),
                ('vote_time', models.CharField(default=None, max_length=12, verbose_name='投票时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
