# Generated by Django 3.2 on 2023-10-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20231023_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_vote',
            field=models.BooleanField(default=False),
        ),
    ]
