# Generated by Django 3.2 on 2023-10-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_myuser_is_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vote',
            field=models.BooleanField(default=False),
        ),
    ]
