# Generated by Django 3.2 on 2023-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_song',
            name='is_collect',
            field=models.BooleanField(default=False),
        ),
    ]
