# Generated by Django 3.2 on 2023-10-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_song_is_collect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_song',
            name='song',
        ),
        migrations.RemoveField(
            model_name='user_song',
            name='user',
        ),
        migrations.AddField(
            model_name='user_song',
            name='song_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user_song',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
