# Generated by Django 3.2 on 2023-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_delete_comment'),
        ('user', '0011_auto_20231028_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Song',
        ),
        migrations.AddField(
            model_name='user',
            name='collect',
            field=models.ManyToManyField(to='index.Song'),
        ),
    ]
