# Generated by Django 3.2 on 2023-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20231028_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collect', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_song',
            },
        ),
    ]
