# Generated by Django 3.2 on 2023-10-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_delete_comment'),
        ('user', '0016_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
