# Generated by Django 3.2 on 2023-10-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_email_users_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.CharField(max_length=30, unique=True, verbose_name='邮箱'),
        ),
    ]
