# Generated by Django 3.2 on 2023-10-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_users_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
