# Generated by Django 3.2 on 2023-10-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='dynamic_vote',
            field=models.IntegerField(default=0, verbose_name='打榜次数'),
        ),
    ]
