# Generated by Django 3.2 on 2023-10-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_dynamic_dynamic_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
